### ISSUE TITLE
Double slash issue

### ISSUE THREAD

**Issue by codeyash** [igordejanovic/Arpeggio#18]
http://pastebin.com/XzXCfXfZ

In somewhere middle of log
str:
 namespace | Fuel\Tasks | ;

In End of log
ASG: Second pass
 
 
{'': '', 'Fuel\\\\Tasks': {'Robots': [['run'], ['protect']]}}

Why double slash between Fuel and Tasks. I guess it is bug.

Python and Grammer is located in public repo
https://bitbucket.org/codeyash/resources/src/7cfb9ba5a0d1de12d2d10734de8e8b6dcb9c6ff3/enrichers/PhpParser/py/php/?at=master
Php.py and grammer.peg

With latest released Arpeggio

**Comment by igordejanovic** [comment]
I guess this was not an issue with Arpeggio.
