### ISSUE TITLE
Matching everything in a subexpression loops infinitely

### ISSUE THREAD

**Issue by rihardsk** [igordejanovic/Arpeggio#26]
I made a simple grammar
```python
grammar = \
        """
        rule <- (subexpression)+;
        subexpression <- r'^.*$';
        """
```
and tried to parse a simple text like so
```python
from arpeggio.peg import ParserPEG
parser = ParserPEG(grammar, "rule")
parsed = parser.parse("something simple")
```

And the process never finishes. It just goes on parsing, steadily filling up the free memory.

**Comment by igordejanovic** [comment]
Hello, rihardsk.

Thanks for the report. It is fixed now on master.

Regards,
Igor
