### ISSUE TITLE
Parsing comments in language?

### ISSUE THREAD

**Issue by TomCrypto** [igordejanovic/Arpeggio#30]
What's a good way to handle general syntactic elements such as comments which can often appear virtually anywhere in the grammar? It seems very tedious to add it to the grammar, and since Arpeggio seems to ignore whitespace (which is generally what you want) it seems that handling comments that run until the end of a line is difficult.

So far I'm just running a preprocessing pass on the source code to strip out comments intelligently, but just wondering if there's a convenient way to add them to the grammar without too much work so I don't have to reimplement basic nesting logic for stripping out comments?

Awesome library otherwise! I was using Parsimonious before but it got in my way often, Arpeggio usually does exactly what you want by default.

**Comment by igordejanovic** [comment]
Hi Thomas,
Thanks. Arpeggio has a support for comments. See [here](http://igordejanovic.net/Arpeggio/configuration/#comment-handling) how to define comment's grammar and configure the parser.

**Comment by TomCrypto** [comment]
Wonderful... great work Igor :+1:

**Comment by igordejanovic** [comment]
Thanks. Depending on your use-case you might find [textX](http://igordejanovic.net/textX/) a better tool. It is built on top of Arpeggio and takes away much of the burden from language/parser developer.

**Comment by TomCrypto** [comment]
Thanks, I looked at it before but it seems a little too complicated for what I want. My language is syntactically simple so I built the semantic parser in a hundred lines or so (including the visitor). Most of the work is in type checking and static analysis :)
