### ISSUE TITLE
fix the docs link

### ISSUE THREAD

**Issue by aolko** [igordejanovic/Arpeggio#41]
currently links to _http://www.igordejanovic.net/iYRTb/LbkRP/Arpeggio/_

**Comment by igordejanovic** [comment]
Which one? I've checked both badge and link in the README and they seem to be OK.

**Comment by aolko** [comment]
when you click in the readme it seems to get to _http://www.igordejanovic.net/iYRTb/LbkRP/Arpeggio/_ and then to the link mentioned above

**Comment by igordejanovic** [comment]
I don't get the same behaviour at my side. No idea. Maybe some link access tracking from GitHub? When I follow the link above a get 404. Try to change browser/device and see if you get the same issue.

**Comment by igordejanovic** [comment]
Just realized that you said that you have been redirected to the above link from the Arpeggio page. Do you got 404 also? Can you start in-browser debugger (Ctrl+Shift+I on Firefox/Chrome) and see on network tab how that redirect happen.

**Comment by aolko** [comment]
Now it should be ok
